[package]
name = "treers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quaternion = "1.0.0"
sdl2 = "0.37.0"
